In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("./all.csv")
df

,Unnamed: 0,description,poste,entreprise,localisation,TYPE DE CONTRAT,ADRESSE,DATE DE PUBLICATION,scrap_timestamp,SALAIRE
0,0,Job Number 23116933\nJob Category Spa\nLocatio...,Attendant - Spa,Marriott International,Plusieurs Emplacements,Temps Plein,"Centre Urbain Nord\nTunis, Tunisia 1082;\nUNAV...",Il y a 6 jours,2023-07-03 17:09:49.094396,NaN
1,1,Job Number 23116947\nJob Category Food and Bev...,1er Commis,Marriott International,Plusieurs Emplacements,Temps Plein,"Centre Urbain Nord\nTunis, Tunisia 1082;\nUNAV...",Il y a 6 jours,2023-07-03 17:09:49.445486,NaN
2,2,Job Number 23116938\nJob Category Food and Bev...,Chef de rang,Marriott International,Plusieurs Emplacements,Temps Plein,"Centre Urbain Nord\nTunis, Tunisia 1082;\nUNAV...",Il y a 6 jours,2023-07-03 17:09:49.839187,NaN
3,3,Overview\nThe Sales administrator & Deal Desk ...,Analyste d'affaires,ADP,"Tunis, Tunis",Temps Plein,"Avenue Zohra Faiza\nTunis, Tunis 1003",Il y a 7 jours,2023-07-03 17:09:50.367181,1 $US–1 000 000 $US Par An
4,4,ADP recruits a Team Leader\nAre you looking to...,Swiss payroll team leader,ADP,"Tunis, Tunis",Temps Plein,"Avenue Zohra Faiza\nTunis, Tunis 1003",Il y a 30+ jours,2023-07-03 17:09:50.807414,1 $US–1 000 000 $US Par An
...,...,...,...,...,...,...,...,...,...,...
95,95,Notre Campagne Alternance pour l'année 2023/20...,Alternance 2023/2024,Vneuron,Tunis,NaN,"Tunis,",Il y a 30+ jours,2023-07-03 17:10:44.274378,NaN
96,96,Please upload your English CV\nMicrosoft SQL D...,Database Administrator,Novelus,"Tunis, Tunisia",NaN,"Tunis, Tunisia -",Il y a 30+ jours,2023-07-03 17:10:44.813129,NaN
97,97,ADP sta reclutando Gestori dei salari \nSei ...,Gestori dei salari,ADP,"Tunis, Tunis",Temps Plein,"Avenue Zohra Faiza\nTunis, Tunis 1003",Il y a 30+ jours,2023-07-03 17:10:45.562801,1 $US–1 000 000 $US Par An
98,98,KPMGaccompagne les sociétés et les groupes nat...,Architecte Technique,SPX,"Tunis, Lac 3",NaN,"Tunis, Lac 3 1074",Il y a 30+ jours,2023-07-03 17:10:46.236994,NaN
99,99,KPMGaccompagne les sociétés et les groupes nat...,CTO,SPX,"Tunis, Lac 3",NaN,"Tunis, Lac 3 1074",Il y a 30+ jours,2023-07-03 17:10:46.838870,NaN

In [3]:
df.shape

(100, 10)